use crate::item_definition;
use serde::{Deserialize, Serialize};
use std::fmt;

item_definition!(
    Item {
        // Ore
        IronOre(name: "Iron Ore", raw),
        CopperOre(name: "Copper Ore", raw),
        Coal(name: "Coal", raw),
        RawQuartz(name: "Raw Quartz", raw),
        CateriumOre(name: "Caterium Ore", raw),
        Limestone(name: "Limestone", raw),
        Bauxite(name: "Bauxite", raw),
        Uranium(name: "Uranium", raw),
        SAMOre(name: "SAMOre", raw),
        Sulfur(name: "Sulfur", raw),

        // Other Resources
        Leaves(name: "Leaves"),
        Wood(name: "Wood"),
        FlowerPetals(name: "Flower Petals"),
        Mycelia(name: "Mycelia"),
        BaconAgaric(name: "Bacon Agaric"),
        BerylNut(name: "Beryl Nut"),
        Paleberry(name: "Paleberry"),
        BluePowerSlug(name: "Blue Power Slug"),
        YellowPowerSlug(name: "Yellow Power Slug"),
        PurplePowerSlug(name: "Purple Power Slug"),
        HogRemains(name: "Hog Remains"),
        PlasmaSplitterRemains(name: "Plasma Splitter Remains"),
        StingerRemains(name: "Stinger Remains"),
        HatcherRemains(name: "Hatcher Remains"),

        // Phase 0
        IronIngot(name: "Iron Ingot"),
        CopperIngot(name: "Copper Ingot"),
        ColorCartridge(name: "Color Cartridge"),
        Biomass(name: "Biomass"),
        SolidBiofuel(name: "Solid Biofuel"),
        Concrete(name: "Concrete"),
        IronPlate(name: "Iron Plate"),
        IronRod(name: "Iron Rod"),
        ReinforcedIronPlate(name: "Reinforced Iron Plate"),
        Screw(name: "Screw"),
        Wire(name: "Wire"),
        Cable(name: "Cable"),
        CopperSheet(name: "Copper Sheet"),
        Rotor(name: "Rotor"),
        ModularFrame(name: "Modular Frame"),

        // Phase 1
        SteelIngot(name: "Steel Ingot"),
        SteelBeam(name: "Steel Beam"),
        SteelPipe(name: "Steel Pipe"),
        EncasedIndustrialBeam(name: "Encased Industrial Beam"),
        Stator(name: "Stator"),
        Motor(name: "Motor"),
        HeavyModularFrame(name: "Heavy Modular Frame"),

        // Phase 2
        CircuitBoard(name: "Circuit Board"),
        Computer(name: "Computer"),
        PetroleumCoke(name: "Petroleum Coke"),
        Plastic(name: "Plastic"),
        Rubber(name: "Rubber"),
        PolymerResin(name: "Polymer Resin"),
        Fabric(name: "Fabric"),

        // Phase 3
        AluminumScrap(name: "Aluminum Scrap"),
        AluminumIngot(name: "Aluminum Ingot"),
        AluminumCasing(name: "Aluminum Casing"),
        AlcladAluminumSheet(name: "Alclad Aluminum Sheet"),
        Battery(name: "Battery"),
        RadioControlUnit(name: "Radio Control Unit"),
        HeatSink(name: "Heat Sink"),
        CoolingSystem(name: "Cooling System"),
        CopperPowder(name: "Copper Powder"),
        ElectromagneticControlRod(name: "Electromagnetic Control Rod"),
        PressureConversionCube(name: "Pressure Conversion Cube"),
        TurboMotor(name: "Turbo Motor"),
        FusedModularFrame(name: "Fused Modular Frame"),
        EncasedUraniumCell(name: "Encased Uranium Cell"),
        EncasedPlutoniumCell(name: "Encased Plutonium Cell"),
        NonFissileUranium(name: "Non-Fissile Uranium"),
        PlutoniumPellet(name: "Plutonium Pellet"),
        UraniumFuelRod(name: "Uranium Fuel Rod"),
        PlutoniumFuelRod(name: "Plutonium Fuel Rod"),
        UraniumWaste(name: "Uranium Waste"),
        PlutoniumWaste(name: "Plutonium Waste"),

        // MAM Research
        PowerShard(name: "Power Shard"),
        AlienProtein(name: "Alien Protein"),
        AlienDNACapsule(name: "Alien DNA Capsule"),
        QuartzCrystal(name: "Quartz Crystal"),
        Silica(name: "Silica"),
        CrystalOscillator(name: "Crystal Oscillator"),
        BlackPowder(name: "Black Powder"),
        SmokelessPowder(name: "Smokeless Powder"),
        CompactedCoal(name: "Compacted Coal"),
        CateriumIngot(name: "Caterium Ingot"),
        Quickwire(name: "Quickwire"),
        AILimiter(name: "AI Limiter"),
        HighSpeedConnector(name: "High-Speed Connector"),
        Supercomputer(name: "Supercomputer"),

        // Packaged Liquids
        EmptyFluidTank(name: "Empty Fluid Tank"),
        EmptyCanister(name: "Empty Canister"),
        PackagedWater(name: "Packaged Water"),
        PackagedCrudeOil(name: "Packaged Crude Oil"),
        PackagedNitrogenGas(name: "Packaged Nitrogen Gas"),
        PackagedLiquidBiofuel(name: "Packaged Liquid Biofuel"),
        PackagedHeavyOilResidue(name: "Packaged Heavy Oil Residue"),
        PackagedFuel(name: "Packaged Fuel"),
        PackagedTurbofuel(name: "Packaged Turbofuel"),
        PackagedAluminaSolution(name: "Packaged Alumina Solution"),
        PackagedSulfuricAcid(name: "Packaged Sulfuric Acid"),
        PackagedNitricAcid(name: "Packaged Nitric Acid"),

        // Equipment
        PortableMiner(name: "Portable Miner"),
        MedicinalInhaler(name: "Medicinal Inhaler"),
        Nobelisk(name: "Nobelisk"),
        GasNobelisk(name: "Gas Nobelisk"),
        PulseNobelisk(name: "Pulse Nobelisk"),
        ClusterNobelisk(name: "Cluster Nobelisk"),
        NukeNobelisk(name: "Nuke Nobelisk"),
        IronRebar(name: "Iron Rebar"),
        StunRebar(name: "Stun Rebar"),
        ShatterRebar(name: "Shatter Rebar"),
        ExplosiveRebar(name: "Explosive Rebar"),
        Ammo(name: "Ammo"),
        HomingAmmo(name: "Homing Ammo"),
        TurboAmmo(name: "Turbo Ammo"),
        GasFilter(name: "Gas Filter"),
        IodineInfusedFilter(name: "Iodine Infused Filter"),

        // Space Elevator Parts
        SmartPlating(name: "Smart Plating"),
        VersatileFramework(name: "Versatile Framework"),
        AutomatedWiring(name: "Automated Wiring"),
        AdaptiveControlUnit(name: "Adaptive Control Unit"),
        ModularEngine(name: "Modular Engine"),
        AssemblyDirectorSystem(name: "Assembly Director System"),
        MagneticFieldGenerator(name: "Magnetic Field Generator"),
        ThermalPropulsionRocket(name: "Thermal Propulsion Rocket"),
        NuclearPasta(name: "Nuclear Pasta")
    }
);
