use crate::item_definition;
use serde::{Deserialize, Serialize};
use std::fmt;

item_definition!(
    Item {
        // Extractable
        IronOre(name: "Iron Ore", extractable, sink_points: 1),
        CopperOre(name: "Copper Ore", extractable, sink_points: 3),
        Coal(name: "Coal", extractable, sink_points: 3),
        RawQuartz(name: "Raw Quartz", extractable, sink_points: 15),
        CateriumOre(name: "Caterium Ore", extractable, sink_points: 7),
        Limestone(name: "Limestone", extractable, sink_points: 2),
        Bauxite(name: "Bauxite", extractable, sink_points: 8),
        Uranium(name: "Uranium", extractable, sink_points: 35),
        SAMOre(name: "SAM Ore", extractable),
        Sulfur(name: "Sulfur", extractable, sink_points: 11),
        Water(name: "Water", extractable, fluid),
        Oil(name: "Oil", extractable, fluid),
        NitrogenGas(name: "Nitrogen Gas", extractable, fluid),

        // Other Resources
        Leaves(name: "Leaves", sink_points: 3),
        Wood(name: "Wood", sink_points: 30),
        FlowerPetals(name: "Flower Petals", sink_points: 10),
        Mycelia(name: "Mycelia", sink_points: 10),
        BaconAgaric(name: "Bacon Agaric"),
        BerylNut(name: "Beryl Nut"),
        Paleberry(name: "Paleberry"),
        BluePowerSlug(name: "Blue Power Slug"),
        YellowPowerSlug(name: "Yellow Power Slug"),
        PurplePowerSlug(name: "Purple Power Slug"),
        HogRemains(name: "Hog Remains"),
        PlasmaSpitterRemains(name: "Plasma Spitter Remains"),
        StingerRemains(name: "Stinger Remains"),
        HatcherRemains(name: "Hatcher Remains"),

        // Phase 0
        IronIngot(name: "Iron Ingot", sink_points: 2),
        CopperIngot(name: "Copper Ingot", sink_points: 6),
        ColorCartridge(name: "Color Cartridge", sink_points: 10),
        Biomass(name: "Biomass", sink_points: 12),
        SolidBiofuel(name: "Solid Biofuel", sink_points: 48),
        Concrete(name: "Concrete", sink_points: 12),
        IronPlate(name: "Iron Plate", sink_points: 6),
        IronRod(name: "Iron Rod", sink_points: 4),
        ReinforcedIronPlate(name: "Reinforced Iron Plate", sink_points: 120),
        Screw(name: "Screw", sink_points: 2),
        Wire(name: "Wire", sink_points: 6),
        Cable(name: "Cable", sink_points: 24),
        CopperSheet(name: "Copper Sheet", sink_points: 24),
        Rotor(name: "Rotor", sink_points: 140),
        ModularFrame(name: "Modular Frame", sink_points: 408),

        // Phase 1
        SteelIngot(name: "Steel Ingot", sink_points: 8),
        SteelBeam(name: "Steel Beam", sink_points: 64),
        SteelPipe(name: "Steel Pipe", sink_points: 24),
        EncasedIndustrialBeam(name: "Encased Industrial Beam", sink_points: 632),
        Stator(name: "Stator", sink_points: 240),
        Motor(name: "Motor", sink_points: 1520),
        HeavyModularFrame(name: "Heavy Modular Frame", sink_points: 11520),

        // Phase 2
        CircuitBoard(name: "Circuit Board", sink_points: 696),
        Computer(name: "Computer", sink_points: 17260),
        PetroleumCoke(name: "Petroleum Coke", sink_points: 20),
        Plastic(name: "Plastic", sink_points: 75),
        Rubber(name: "Rubber", sink_points: 60),
        PolymerResin(name: "Polymer Resin", sink_points: 12),
        Fabric(name: "Fabric", sink_points: 140),
        LiquidBiofuel(name: "Liquid Biofuel", fluid),
        HeavyOilResidue(name: "Heavy Oil Residue", fluid),
        Fuel(name: "Fuel", fluid),

        // Phase 3
        AluminumScrap(name: "Aluminum Scrap", sink_points: 27),
        AluminumIngot(name: "Aluminum Ingot", sink_points: 131),
        AluminumCasing(name: "Aluminum Casing", sink_points: 393),
        AlcladAluminumSheet(name: "Alclad Aluminum Sheet", sink_points: 266),
        Battery(name: "Battery", sink_points: 465),
        RadioControlUnit(name: "Radio Control Unit", sink_points: 19600),
        HeatSink(name: "Heat Sink", sink_points: 2804),
        CoolingSystem(name: "Cooling System", sink_points: 12006),
        CopperPowder(name: "Copper Powder", sink_points: 72),
        ElectromagneticControlRod(name: "Electromagnetic Control Rod", sink_points: 2560),
        PressureConversionCube(name: "Pressure Conversion Cube", sink_points: 257312),
        TurboMotor(name: "Turbo Motor", sink_points: 242720),
        FusedModularFrame(name: "Fused Modular Frame", sink_points: 62840),
        EncasedUraniumCell(name: "Encased Uranium Cell", sink_points: 147),
        EncasedPlutoniumCell(name: "Encased Plutonium Cell"),
        NonFissileUranium(name: "Non-Fissile Uranium"),
        PlutoniumPellet(name: "Plutonium Pellet"),
        UraniumFuelRod(name: "Uranium Fuel Rod", sink_points: 44092),
        PlutoniumFuelRod(name: "Plutonium Fuel Rod", sink_points: 153184),
        UraniumWaste(name: "Uranium Waste"),
        PlutoniumWaste(name: "Plutonium Waste"),
        AluminaSolution(name: "Alumina Solution", fluid),
        SulfuricAcid(name: "Sulfuric Acid", fluid),
        NitricAcid(name: "Nitric Acid", fluid),

        // MAM Research
        PowerShard(name: "Power Shard"),
        AlienProtein(name: "Alien Protein"),
        AlienDNACapsule(name: "Alien DNA Capsule", sink_points: 1000),
        QuartzCrystal(name: "Quartz Crystal", sink_points: 50),
        Silica(name: "Silica", sink_points: 20),
        CrystalOscillator(name: "Crystal Oscillator", sink_points: 3072),
        BlackPowder(name: "Black Powder", sink_points: 14),
        SmokelessPowder(name: "Smokeless Powder", sink_points: 58),
        CompactedCoal(name: "Compacted Coal", sink_points: 28),
        CateriumIngot(name: "Caterium Ingot", sink_points: 42),
        Quickwire(name: "Quickwire", sink_points: 17),
        AILimiter(name: "AI Limiter", sink_points: 920),
        HighSpeedConnector(name: "High-Speed Connector", sink_points: 3776),
        Supercomputer(name: "Supercomputer", sink_points: 99576),
        Turbofuel(name: "Turbofuel", fluid),

        // Packaged Liquids
        EmptyFluidTank(name: "Empty Fluid Tank", sink_points: 225),
        EmptyCanister(name: "Empty Canister", sink_points: 60),
        PackagedWater(name: "Packaged Water", sink_points: 130),
        PackagedOil(name: "Packaged Oil", sink_points: 180),
        PackagedNitrogenGas(name: "Packaged Nitrogen Gas", sink_points: 312),
        PackagedLiquidBiofuel(name: "Packaged Liquid Biofuel", sink_points: 370),
        PackagedHeavyOilResidue(name: "Packaged Heavy Oil Residue", sink_points: 180),
        PackagedFuel(name: "Packaged Fuel", sink_points: 270),
        PackagedTurbofuel(name: "Packaged Turbofuel", sink_points: 570),
        PackagedAluminaSolution(name: "Packaged Alumina Solution", sink_points: 160),
        PackagedSulfuricAcid(name: "Packaged Sulfuric Acid", sink_points: 152),
        PackagedNitricAcid(name: "Packaged Nitric Acid", sink_points: 412),

        // Equipment
        PortableMiner(name: "Portable Miner", sink_points: 60),
        MedicinalInhaler(name: "Medicinal Inhaler", sink_points: 125),
        Nobelisk(name: "Nobelisk", sink_points: 152),
        GasNobelisk(name: "Gas Nobelisk", sink_points: 544),
        PulseNobelisk(name: "Pulse Nobelisk", sink_points: 1533),
        ClusterNobelisk(name: "Cluster Nobelisk", sink_points: 1376),
        NukeNobelisk(name: "Nuke Nobelisk", sink_points: 19600),
        IronRebar(name: "Iron Rebar", sink_points: 8),
        StunRebar(name: "Stun Rebar", sink_points: 186),
        ShatterRebar(name: "Shatter Rebar", sink_points: 332),
        ExplosiveRebar(name: "Explosive Rebar", sink_points: 360),
        RifleAmmo(name: "Rifle Ammo", sink_points: 25),
        HomingRifleAmmo(name: "Homing Rifle Ammo", sink_points: 855),
        TurboRifleAmmo(name: "Turbo Rifle Ammo", sink_points: 120),
        GasFilter(name: "Gas Filter", sink_points: 830),
        IodineInfusedFilter(name: "Iodine Infused Filter", sink_points: 2718),
        Beacon(name: "Beacon", sink_points: 320),

        // Space Elevator Parts
        SmartPlating(name: "Smart Plating", sink_points: 520),
        VersatileFramework(name: "Versatile Framework", sink_points: 1176),
        AutomatedWiring(name: "Automated Wiring", sink_points: 1440),
        AdaptiveControlUnit(name: "Adaptive Control Unit", sink_points: 86120),
        ModularEngine(name: "Modular Engine", sink_points: 9960),
        AssemblyDirectorSystem(name: "Assembly Director System", sink_points: 543632),
        MagneticFieldGenerator(name: "Magnetic Field Generator", sink_points: 15650),
        ThermalPropulsionRocket(name: "Thermal Propulsion Rocket", sink_points: 732956),
        NuclearPasta(name: "Nuclear Pasta", sink_points: 543424),

        // ficsmas
        FicsmasGift(name: "FICSMAS Gift", sink_points: 1),
        FicsmasTreeBranch(name: "FICSMAS Tree Branch", sink_points: 1),
        CandyCane(name: "Candy Cane", sink_points: 1),
        FicsmasBow(name: "FICSMAS Bow", sink_points: 1),
        RedFicsmasOrnament(name: "Red FICSMAS Ornament", sink_points: 1),
        BlueFicsmasOrnament(name: "Blue FICSMAS Ornament", sink_points: 1),
        IronFicsmasOrnament(name: "Iron FICSMAS Ornament", sink_points: 1),
        CopperFicsmasOrnament(name: "Copper FICSMAS Ornament", sink_points: 1),
        FicsmasOrnamentBundle(name: "FICSMAS Ornament Bundle", sink_points: 1),
        ActualSnow(name: "Actual Snow", sink_points: 1),
        FicsmasDecoration(name: "FICSMAS Decoration", sink_points: 1),
        Snowball(name: "Snowball", sink_points: 1),
        FicsmasWonderStar(name: "FICSMAS Wonder Star", sink_points: 1),
        SweetFireworks(name: "Sweet Fireworks", sink_points: 18),
        FancyFireworks(name: "Fancy Fireworks", sink_points: 14),
        SparklyFireworks(name: "Sparkly Fireworks", sink_points: 10)
    }
);
